### ISSUE TITLE
Version 3.0.0 checklist

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/processx#77]
- [x] customizable `stdout` and `stderr` encoding
- [x] convert docs to markdown
- [x] solaris fix
- [x] dr memory runs
- [x] platform checks
- [x] test coverage (close to) 100%
- [x] update connection docs everywhere: README, manual, DESCRIPTION (?)
- [x] update internal docs
- [x] update NEWS
